services:
  - type: web
    name: bot-semillero-agil
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
